### ISSUE TITLE
Add a configuration file

### ISSUE THREAD

**Issue by MartinIngesen** [kaosu/Sleuth#3]
Hey!

Since you require a Google API key for the code to work, I would suggest that you create a configuration file for that. YAML, JSON or INI files are great for this.

As a side note:
Lets say you name the config file `config.json`. Add that filename to the `.gitignore`-file. Then create and commit a file called `config.example.json` instead without your real credentials. Then require the user to rename and add their credentials to that file. This way you can avoid accidentally uploading a valid credential key!

**Comment by kaosu** [comment]
Thank you for the feedback. I will add this feature to Sleuth over the summer when I have more time. All of your other issues have been addressed.
